#!/bin/bash -e

. config.conf

NDK_PATH=${NDK_DIR_NAME}
OPENSSL_PATH=$(pwd)/../
# GCC_VERSION=$(gcc --version | grep gcc | awk '{print $4}' | cut -d'.' -f1,2)
GCC_VERSION=${ANDROID_BUILD_GCC_VERSION}
LIB_PATH="${OPENSSL_BUILD_OUT_PATH}/libs"
LOG_PATH="${OPENSSL_BUILD_OUT_PATH}/logs"

echo $NDK_PATH
echo $OPENSSL_PATH
echo $OPENSSL_BUILD_OUT_PATH

rm -rf "${OPENSSL_BUILD_OUT_PATH}"
mkdir -p "${LIB_PATH}"
mkdir -p "${LOG_PATH}"

for arch in "${TARGET_ARCHS[@]}"
do
    echo "Building OpenSSL for target arch $arch ..."
    ./openssl-build ${NDK_PATH} ${OPENSSL_PATH} ${TARGET_ANDROID_API} \
                    ${arch} ${GCC_VERSION} "${LIB_PATH}/${arch}" \
                    >>"${LOG_PATH}/${arch}.log" 2>&1
done

echo "Finished building OpenSSL! Check output folder: ${OPENSSL_BUILD_OUT_PATH}"
